### ISSUE TITLE
NowPlaying を行うアカウントを切り替えれるようにしたい

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato-NowPlaying#15]
~~interface を与えることによって、拡張性を持たせれば嬉しいかも。~~

**Comment by marihachi** [comment]
ディレクトリからdllを列挙して動的にインスタンスを作るなどの処理が必要かも

**Comment by marihachi** [comment]
切り替えができる必要があるかどうかも含めて検討したい

**Comment by marihachi** [comment]
メインフォーム上で投稿先サービスを選択できると便利そう(複数、単一)

**Comment by marihachi** [comment]
設定画面上から有効化状態を切り替えられるようになった
