### ISSUE TITLE
各種 SNS に Connect した後、接続完了したか状況がわからない

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato-NowPlaying#24]
Connect を押下し認証完了したならば、「認証完了」といった形で
ユーザに伝えるべきと思う。

現状の認証後 UI
![2018-06-03 1](https://user-images.githubusercontent.com/18462305/40882332-9b20a8a4-6719-11e8-8dc0-d1756196567b.png)

**Comment by marihachi** [comment]
連携状態を判断する方法も考えていかないといけない
たとえばAPIキーが有効であることを確認するために単純なAPIアクセスをしてみる など

**Comment by marihachi** [comment]
未接続、有効、無効 の３つの状態で確認できるようになった
