### ISSUE TITLE
音声認識をさせたい

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato-NowPlaying#3]
* 再生
* 停止
* 次の曲 とか実装出来ればと思ってます。

SpeechLib でこの辺りは実装したことあるので割りとすんなり行けるかなと。

**Comment by Asteriskx** [comment]
可愛いボイスが欲しい(切実)

**Comment by marihachi** [comment]
なうぷれアプリという意味であんまり重要な要素じゃない気がする
音声の再生もそうだけど、拡張機能で実装できるのが理想

**Comment by Asteriskx** [comment]
プラグイン的な感じだよね

**Comment by marihachi** [comment]
多分サポートしないので閉じます
