### ISSUE TITLE
misskey.xyz以外のMisskeyにもなうぷれを投稿できるようにする

### ISSUE THREAD

**Issue by marihachi** [Legato-Dev/Legato-NowPlaying#32]
インスタンスが増えてきたように思う

**Comment by Asteriskx** [comment]
これは、対応必要そうだね

**Comment by marihachi** [comment]
連携アプリ登録のAPIコールをアプリ上からするように変更する予定

**Comment by marihachi** [comment]
Misskeyの公式インスタンスが.xyzから.ioに移行されるらしいのでこれの対応が必須に

**Comment by marihachi** [comment]
これ現時点でもう実装できているんだけど、misskeyのバージョン(v10とかv11)とかによってアプリ権限の名前が変わっていたり、少し対応できていない部分がまだある

**Comment by marihachi** [comment]
対応自体は完了。
使用してるMisqバージョンのリリース待ち

**Comment by marihachi** [comment]
なった
