### ISSUE TITLE
Frost API 対応

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato-NowPlaying#33]
#14

**Comment by Asteriskx** [comment]
2018-08-14 0120 時点
現行の Frost API を用いて、Text ベースの投稿を確認済み。
やったぜ。

**Comment by marihachi** [comment]
一旦、作業ブランチ立ててそこにコミットしてほしい。
とりあえず荒削りでいいので。
認可時のコールバックURLの所とかFrost-Web側の対応が必要な部分もあるので。

**Comment by marihachi** [comment]
一旦保留で
