### ISSUE TITLE
Service に関して

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato-NowPlaying#35]
接続していないサービスがあるのに
NowPlaying 実行すると、全てのサービスが動作している状態になっている

![image](https://user-images.githubusercontent.com/18462305/44070819-ea866188-9fc0-11e8-8987-7c5b00c8d6eb.png)

![image](https://user-images.githubusercontent.com/18462305/44070846-0e79c684-9fc1-11e8-9fad-4b30ff8685af.png)

**Comment by marihachi** [comment]
なんで

**Comment by Asteriskx** [comment]
Accounts.cs
* 各サービスの Enabled を見に行ってるけど、
　多分これ設定関係なしに true になってるからだと思う
　　→ 基底クラス側のプロパティ初期値で true 設定してたはず...

![image](https://user-images.githubusercontent.com/18462305/44071012-c2d9d43e-9fc1-11e8-9cfe-516e231686a8.png)

**Comment by Asteriskx** [comment]
うん、やっぱりそうだった
`public bool Enabled { get; set; } = true;`
これのせい

登録していない/Json ファイル設定していないものでも
このプロパティが `true` になってるせいで、常に `Enable=true` になる

![image](https://user-images.githubusercontent.com/18462305/44071171-8f0660ae-9fc2-11e8-8707-f2ee0fed2fe5.png)

**Comment by marihachi** [comment]
この修正は直接masterに入れて良いと思うよ
