### ISSUE TITLE
スリープ復帰後、曲情報が更新されない

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato-NowPlaying#41]
Legato の構造上、ウィンドウメッセージを介して曲情報を更新しているが、
スリープしている際は、上記メッセージが飛ばないので更新がストップしているものと思われる。

**Comment by marihachi** [comment]
あてすと氏からの情報提供
Microsoft.Win32.SystemEvents.PowerModeChanged
スリープ復帰イベントらしいです

このタイミングに、曲情報を取得しなおせば解決しそう

**Comment by Asteriskx** [comment]
そうだね。それで対応するわ
https://github.com/Asteriskx/Kisaragi/issues/28
Kisaragi でも全く同じことやろうとしてたわｗ

**Comment by Asteriskx** [comment]
上手くいったので、こみっとするー
