### ISSUE TITLE
Twitter を見切るかもしれない

### ISSUE THREAD

**Issue by Asteriskx** [Legato-Dev/Legato-NowPlaying#9]
♰終焉の時♰が来たようだ。
Twitter を見切るのであれば、 CoreTweet を パッケージから除外する必要がある。

**Comment by marihachi** [comment]
よりコンパクトなTwitterライブラリ実装に移行することで、Twitterサポートのコストを下げる方針になりました。

**Comment by marihachi** [comment]
関連: #28 
こちらは閉じます
